### ISSUE TITLE
레벨 정보 페이지에서 언어를 변경해도 곡 길이 단위(분)이 바뀌지 않음

### ISSUE THREAD

**Issue by ppapman1** [ADOFAI-gg/ADOFAI-gg-Web#44]

**Comment by ppapman1** [comment]
https://cdn.discordapp.com/attachments/1079767475702472766/1079767475983503501/Screen_Recording_20230227_230815_Chrome.mp4

**Comment by wjdgustn** [comment]
https://user-images.githubusercontent.com/34962071/221587139-532bda0e-2740-425d-b189-97d5a6b69f32.mp4
